plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.q3rvo.erciyesflight'
    compileSdk 35

    defaultConfig {
        applicationId 'com.q3rvo.erciyesflight'
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName '1.4'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
