package com.q3rvo.erciyesflight

import android.content.Context
import android.graphics.*
import android.view.*
import kotlin.math.*

class CleanGameView(context: Context) : View(context), Choreographer.FrameCallback {
    companion object {
        private const val W=1080f; private const val H=1920f; private const val GROUND=1690f
        private const val BIRD_X=300f; private const val BIRD_W=126f; private const val BIRD_H=99f
        private const val GRAVITY=2500f; private const val FLAP=-820f; private const val SPEED=430f
        private const val GAP=600f; private const val PIPE_W=160f; private const val SPACING=620f
        private const val FIRST=1550f; private const val TRIGGER=480f; private const val GAP_MIN=700f; private const val GAP_MAX=990f
        private const val TOP=Color.rgb(67,174,226); private const val BOTTOM=Color.rgb(222,242,246)
        private const val PRIMARY=Color.rgb(28,77,108); private const val ACCENT=Color.rgb(236,164,52)
        private const val TEXT=Color.rgb(28,58,76); private const val MUTED=Color.rgb(92,119,133)
        private const val PIPE1=Color.rgb(88,184,153); private const val PIPE2=Color.rgb(39,119,105)
    }
    private enum class State { MENU, SETTINGS, PLAYING, GAMEOVER }
    private val prefs=context.getSharedPreferences("game",Context.MODE_PRIVATE)
    private val bird=BitmapFactory.decodeResource(resources,R.drawable.player_bird)
    private val birdFrames=makeBirdFrames(bird)
    private val spawner=PipeSpawner(W,H,SPACING,PIPE_W,FIRST,TRIGGER,GAP_MIN,GAP_MAX,835f)
    private val sounds=PremiumSoundEngine(); private val choreographer=Choreographer.getInstance()
    private val sky=Paint(1); private val cloud=Paint(1); private val mountain=Paint(1); private val city=Paint(1); private val ground=Paint(1)
    private val pipe=Paint(1); private val pipeHi=Paint(1); private val birdPaint=Paint(Paint.ANTI_ALIAS_FLAG or Paint.FILTER_BITMAP_FLAG).apply{alpha=255;isFilterBitmap=true;isDither=true}
    private val hud=Paint(1); private val text=Paint(1); private val shadow=Paint(1); private val overlay=Paint(1); private val icon=Paint(1)
    private val dst=RectF(); private val hit=RectF(); private val hitA=RectF(); private val hitB=RectF(); private val scoreRect=RectF(); private val play=RectF(); private val secondary=RectF(); private val settings=RectF(); private val panel=RectF(); private val record=RectF()
    private val mountainPath=Path(); private val snowPath=Path(); private val cityPath=Path()
    private val bold=Typeface.create("sans-serif",Typeface.BOLD); private val normal=Typeface.create("sans-serif",Typeface.NORMAL)
    private val skyShader=LinearGradient(0f,0f,0f,H,TOP,BOTTOM,Shader.TileMode.CLAMP); private val pipeShader=LinearGradient(0f,0f,PIPE_W,0f,PIPE1,PIPE2,Shader.TileMode.CLAMP)
    private var state=State.MENU; private var score=0; private var high=prefs.getInt("high",0); private var previousHigh=high; private var newRecord=false; private var muted=prefs.getBoolean("muted",false); private var haptic=prefs.getBoolean("haptic",true)
    private var birdY=835f; private var velocity=0f; private var time=0f; private var gameOverTime=0f; private var pressTime=0f; private var pressed=0; private var safeTop=0f; private var safeBottom=0f; private var scale=1f; private var ox=0f; private var oy=0f
    private var running=false; private var framePosted=false; private var lastFrame=0L; private var debugFrames=0L; private var debugSeconds=0f; private var debugMax=0f; private var debugCallbacks=0L
    init {
        isFocusable=true; setLayerType(LAYER_TYPE_HARDWARE,null); text.typeface=bold; shadow.color=Color.argb(45,24,63,79); icon.style=Paint.Style.STROKE; icon.strokeCap=Paint.Cap.ROUND
        mountainPath.moveTo(0f,810f); mountainPath.cubicTo(180f,720f,315f,770f,425f,690f); mountainPath.lineTo(540f,385f); mountainPath.cubicTo(660f,680f,775f,735f,875f,670f); mountainPath.cubicTo(965f,615f,1030f,715f,W,745f); mountainPath.lineTo(W,1080f); mountainPath.lineTo(0f,1080f); mountainPath.close()
        snowPath.moveTo(475f,555f); snowPath.lineTo(540f,385f); snowPath.lineTo(610f,555f); snowPath.lineTo(573f,526f); snowPath.lineTo(540f,454f); snowPath.lineTo(507f,526f); snowPath.close()
        cityPath.moveTo(0f,1040f); cityPath.lineTo(90f,960f); cityPath.lineTo(175f,1040f); cityPath.lineTo(260f,930f); cityPath.lineTo(345f,1040f); cityPath.lineTo(430f,965f); cityPath.lineTo(515f,1040f); cityPath.lineTo(600f,905f); cityPath.lineTo(685f,1040f); cityPath.lineTo(770f,945f); cityPath.lineTo(855f,1040f); cityPath.lineTo(940f,920f); cityPath.lineTo(1025f,1040f); cityPath.lineTo(W,980f); cityPath.lineTo(W,1135f); cityPath.lineTo(0f,1135f); cityPath.close()
        startLoop()
    }
    override fun onAttachedToWindow(){super.onAttachedToWindow();startLoop()}
    override fun onDetachedFromWindow(){stopLoop();sounds.release();birdFrames.forEach{if(it!==bird&&!it.isRecycled)it.recycle()};if(!bird.isRecycled)bird.recycle();super.onDetachedFromWindow()}
    fun pauseLoop()=stopLoop(); fun resumeLoop(){lastFrame=0L;startLoop()}
    fun setSafeInsets(top:Int,bottom:Int){safeTop=top.toFloat();safeBottom=bottom.toFloat();recalc(width,height);invalidate()}
    private fun startLoop(){if(running)return;running=true;lastFrame=0L;postFrame()}
    private fun stopLoop(){running=false;if(framePosted){choreographer.removeFrameCallback(this);framePosted=false};lastFrame=0L}
    private fun postFrame(){if(!running||framePosted)return;framePosted=true;choreographer.postFrameCallback(this)}
    override fun doFrame(t:Long){framePosted=false;if(!running)return;val raw=if(lastFrame==0L)0f else(t-lastFrame)/1_000_000_000f;lastFrame=t;val dt=raw.coerceIn(0f,.033f);if(BuildConfig.DEBUG){debugFrames++;debugSeconds+=raw.coerceAtLeast(0f);debugMax=max(debugMax,raw);debugCallbacks++;if(debugFrames%600L==0L){val avg=debugSeconds/debugFrames;android.util.Log.d("ErciyesPerf","avgFPS=%.1f maxFrame=%.1fms callbacks=%d pipes=%d".format(if(avg>0f)1f/avg else 0f,debugMax*1000f,debugCallbacks,spawner.pipes.size))}};update(dt);invalidate();postFrame()}
    private fun update(dt:Float){time+=dt;pressTime=max(0f,pressTime-dt);when(state){State.PLAYING->{velocity+=GRAVITY*dt;birdY+=velocity*dt;spawner.update(dt,SPEED);for(p in spawner.pipes)if(!p.passed&&p.x+PIPE_W<BIRD_X&&spawner.markPassed(p)){score++;sound(2);buzz(HapticFeedbackConstants.KEYBOARD_TAP)};if(collides())gameOver()};State.GAMEOVER->{gameOverTime=min(1f,gameOverTime+dt*4f)};else->{}}}
    private fun collides():Boolean{hit.set(BIRD_X-BIRD_W*.34f,birdY-BIRD_H*.36f,BIRD_X+BIRD_W*.34f,birdY+BIRD_H*.36f);if(hit.top<45f||hit.bottom>GROUND)return true;val half=GAP*.5f;for(p in spawner.pipes){hitA.set(p.x,0f,p.x+PIPE_W,p.gapCenter-half);hitB.set(p.x,p.gapCenter+half,p.x+PIPE_W,GROUND);if(RectF.intersects(hit,hitA)||RectF.intersects(hit,hitB))return true};return false}
    private fun gameOver(){if(state!=State.PLAYING)return;state=State.GAMEOVER;gameOverTime=0f;newRecord=score>previousHigh;if(newRecord){high=score;prefs.edit().putInt("high",high).apply()};sound(6);buzz(HapticFeedbackConstants.LONG_PRESS)}
    private fun startGame(){state=State.PLAYING;score=0;previousHigh=high;newRecord=false;birdY=835f;velocity=0f;time=0f;spawner.reset();sound(5);buzz(HapticFeedbackConstants.VIRTUAL_KEY)}
    private fun menu(){state=State.MENU;spawner.clear();pressed=0;pressTime=0f}
    private fun sound(id:Int){if(!muted)sounds.play(id)};private fun buzz(id:Int){if(haptic&&isHapticFeedbackEnabled)performHapticFeedback(id)}
    private fun recalc(w:Int,h:Int){if(w<=0||h<=0)return;val usable=(h-safeTop-safeBottom).coerceAtLeast(1f);scale=min(w/W,usable/H);ox=(w-W*scale)*.5f;oy=safeTop+(usable-H*scale)*.5f}
    override fun onSizeChanged(w:Int,h:Int,ow:Int,oh:Int){super.onSizeChanged(w,h,ow,oh);recalc(w,h)}
    override fun onTouchEvent(e:MotionEvent):Boolean{if(e.actionMasked!=MotionEvent.ACTION_DOWN)return true;val x=(e.x-ox)/scale;val y=(e.y-oy)/scale;when(state){State.MENU->if(play.contains(x,y))startGame()else if(settings.contains(x,y))state=State.SETTINGS;State.SETTINGS->if(play.contains(x,y)){haptic=!haptic;prefs.edit().putBoolean("haptic",haptic).apply()}else if(secondary.contains(x,y)){muted=!muted;prefs.edit().putBoolean("muted",muted).apply()}else if(settings.contains(x,y))menu();State.PLAYING->{velocity=FLAP;sound(1);buzz(HapticFeedbackConstants.KEYBOARD_TAP)};State.GAMEOVER->if(play.contains(x,y))startGame()else if(secondary.contains(x,y))menu()};return true}
    override fun onDraw(c:Canvas){super.onDraw(c);c.drawColor(BOTTOM);c.save();c.translate(ox,oy);c.scale(scale,scale);world(c);when(state){State.MENU->menuDraw(c);State.SETTINGS->settingsDraw(c);State.PLAYING->hudDraw(c);State.GAMEOVER->{hudDraw(c);gameOverDraw(c)}};c.restore()}
    private fun world(c:Canvas){sky.shader=skyShader;sky.alpha=255;c.drawRect(0f,0f,W,H,sky);sky.shader=null;clouds(c);mountain.color=Color.rgb(94,155,192);mountain.alpha=255;c.drawPath(mountainPath,mountain);mountain.color=Color.rgb(246,251,251);c.drawPath(snowPath,mountain);city.color=Color.rgb(126,159,172);city.alpha=205;c.drawPath(cityPath,city);city.color=Color.rgb(174,195,201);city.alpha=180;c.drawRect(450f,940f,630f,1045f,city);c.drawOval(460f,830f,620f,955f,city);c.drawRect(485f,790f,505f,1045f,city);c.drawRect(575f,790f,595f,1045f,city);ground.color=Color.rgb(82,166,93);ground.alpha=255;c.drawRect(0f,GROUND,W,GROUND+40f,ground);ground.color=Color.rgb(238,211,158);c.drawRect(0f,GROUND+40f,W,H,ground);pipes(c);if(state!=State.SETTINGS)birdDraw(c,state==State.MENU)}
    private fun clouds(c:Canvas){cloud(c,120f-time*7f,245f,100f);cloud(c,730f-time*4f,345f,115f);cloud(c,1270f-time*2.5f,175f,80f)}
    private fun cloud(c:Canvas,x:Float,y:Float,s:Float){val xx=((x+1400f)%1400f)-150f;cloud.color=Color.WHITE;cloud.alpha=205;c.drawCircle(xx,y,s*.30f,cloud);c.drawCircle(xx+s*.30f,y-s*.09f,s*.39f,cloud);c.drawCircle(xx+s*.60f,y,s*.27f,cloud);c.drawRoundRect(xx-s*.27f,y,xx+s*.72f,y+s*.20f,s*.1f,s*.1f,cloud)}
    private fun pipes(c:Canvas){val half=GAP*.5f;for(p in spawner.pipes){pipe.shader=pipeShader;pipe.alpha=255;c.drawRoundRect(p.x,0f,p.x+PIPE_W,p.gapCenter-half,15f,15f,pipe);c.drawRoundRect(p.x,p.gapCenter+half,p.x+PIPE_W,GROUND,15f,15f,pipe);pipe.shader=null;pipe.color=Color.rgb(75,139,177);c.drawRoundRect(p.x-14f,p.gapCenter-half-48f,p.x+PIPE_W+14f,p.gapCenter-half,14f,14f,pipe);c.drawRoundRect(p.x-14f,p.gapCenter+half,p.x+PIPE_W+14f,p.gapCenter+half+48f,14f,14f,pipe);pipeHi.color=Color.rgb(141,221,190);pipeHi.alpha=125;c.drawRoundRect(p.x+13f,8f,p.x+29f,max(9f,p.gapCenter-half-8f),7f,7f,pipeHi);c.drawRoundRect(p.x+13f,p.gapCenter+half+8f,p.x+29f,GROUND-8f,7f,7f,pipeHi)}}
    private fun birdDraw(c:Canvas,menu:Boolean){birdPaint.alpha=255;birdPaint.colorFilter=null;val y=if(menu)735f+sin(time*2f)*9f else birdY;val f=birdFrames[((time*8f).toInt()%birdFrames.size+birdFrames.size)%birdFrames.size];dst.set(BIRD_X-BIRD_W*.5f,y-BIRD_H*.5f,BIRD_X+BIRD_W*.5f,y+BIRD_H*.5f);c.save();c.rotate(if(menu)sin(time*1.5f)*4f else(velocity/24f).coerceIn(-20f,22f),BIRD_X,y);c.drawBitmap(f,null,dst,birdPaint);c.restore()}
    private fun hudDraw(c:Canvas){scoreRect.set(430f,58f,650f,166f);hud.color=Color.WHITE;hud.alpha=240;c.drawRoundRect(scoreRect,28f,28f,hud);text.alpha=255;text.color=TEXT;text.typeface=bold;text.textAlign=Paint.Align.CENTER;text.textSize=68f;c.drawText(score.toString(),540f,136f,text)}
    private fun menuDraw(c:Canvas){panel.set(110f,165f,970f,1645f);hud.color=Color.WHITE;hud.alpha=190;c.drawRoundRect(panel,56f,56f,hud);text.typeface=bold;text.color=PRIMARY;text.textSize=84f;text.textAlign=Paint.Align.CENTER;c.drawText("ERCİYES",540f,385f,text);text.typeface=normal;text.color=ACCENT;text.textSize=54f;c.drawText("UÇUŞU",540f,445f,text);text.color=MUTED;text.textSize=29f;c.drawText("Kayseri'nin üzerinde ne kadar uçabilirsin?",540f,885f,text);play.set(280f,1010f,800f,1150f);secondary.set(350f,1190f,730f,1300f);settings.set(455f,1360f,625f,1465f);button(c,play,"OYNA",true);button(c,secondary,muted?"SES KAPALI":"SES AÇIK",false);gear(c,settings);text.typeface=bold;text.color=TEXT;text.textSize=27f;c.drawText("EN YÜKSEK SKOR  $high",540f,1550f,text)}
    private fun settingsDraw(c:Canvas){panel.set(160f,620f,920f,1395f);hud.color=Color.WHITE;hud.alpha=245;c.drawRoundRect(panel,48f,48f,hud);text.typeface=bold;text.color=TEXT;text.textSize=48f;text.textAlign=Paint.Align.CENTER;c.drawText("AYARLAR",540f,735f,text);play.set(270f,820f,810f,960f);secondary.set(270f,1000f,810f,1140f);settings.set(455f,1220f,625f,1325f);button(c,play,if(haptic)"TİTREŞİM AÇIK" else "TİTREŞİM KAPALI",true);button(c,secondary,if(muted)"SES KAPALI" else "SES AÇIK",false);button(c,settings,"GERİ",false)}
    private fun button(c:Canvas,r:RectF,label:String,primary:Boolean){shadow.alpha=35;c.drawRoundRect(r.left+4f,r.top+7f,r.right+4f,r.bottom+7f,30f,30f,shadow);hud.color=if(primary)ACCENT else Color.rgb(238,247,249);hud.alpha=255;c.drawRoundRect(r,30f,30f,hud);text.typeface=bold;text.textAlign=Paint.Align.CENTER;text.textSize=if(primary)48f else 28f;text.color=if(primary)PRIMARY else TEXT;c.drawText(label,r.centerX(),r.centerY()+text.textSize*.34f,text)}
    private fun gear(c:Canvas,r:RectF){hud.color=Color.rgb(238,247,249);hud.alpha=255;c.drawCircle(r.centerX(),r.centerY(),44f,hud);icon.color=PRIMARY;icon.alpha=255;icon.strokeWidth=6f;c.drawCircle(r.centerX(),r.centerY(),17f,icon);for(i in 0 until 8){val a=i*PI.toFloat()/4f;c.drawLine(r.centerX()+cos(a)*24f,r.centerY()+sin(a)*24f,r.centerX()+cos(a)*32f,r.centerY()+sin(a)*32f,icon)}}
    private fun gameOverDraw(c:Canvas){overlay.color=Color.rgb(20,58,74);overlay.alpha=(145f*min(1f,gameOverTime*2.2f)).toInt();c.drawRect(0f,0f,W,H,overlay);panel.set(180f,565f,900f,1285f);hud.color=Color.WHITE;hud.alpha=255;c.drawRoundRect(panel,46f,46f,hud);text.typeface=bold;text.color=TEXT;text.textAlign=Paint.Align.CENTER;text.textSize=56f;c.drawText("OYUN BİTTİ",540f,670f,text);text.typeface=normal;text.color=MUTED;text.textSize=25f;c.drawText("Uçuş tamamlandı",540f,715f,text);text.typeface=bold;text.color=PRIMARY;text.textSize=104f;c.drawText(score.toString(),540f,845f,text);text.typeface=normal;text.color=MUTED;text.textSize=25f;c.drawText("SKOR",540f,890f,text);text.textAlign=Paint.Align.LEFT;text.textSize=26f;c.drawText("EN YÜKSEK",340f,965f,text);text.textAlign=Paint.Align.RIGHT;text.typeface=bold;text.color=TEXT;c.drawText(high.toString(),740f,965f,text);if(newRecord){record.set(370f,998f,710f,1056f);hud.color=Color.rgb(255,244,215);hud.alpha=255;c.drawRoundRect(record,28f,28f,hud);text.textAlign=Paint.Align.CENTER;text.color=Color.rgb(170,112,24);text.textSize=24f;c.drawText("YENİ REKOR",540f,1037f,text)};play.set(280f,1090f,800f,1190f);secondary.set(325f,1205f,755f,1270f);button(c,play,"TEKRAR OYNA",true);button(c,secondary,"ANA MENÜ",false)}
    private fun makeBirdFrames(src:Bitmap):Array<Bitmap>{val out=ArrayList<Bitmap>(3);for(s in floatArrayOf(.97f,1f,1.03f)){val m=Matrix();m.setScale(1f,s,src.width/2f,src.height/2f);out+=Bitmap.createBitmap(src,0,0,src.width,src.height,m,true)};return out.toTypedArray()}
}
