package com.q3rvo.erciyesflight

import android.content.Context
import android.graphics.*
import android.view.*
import kotlin.math.*

class CleanGameView(context: Context) : View(context), Choreographer.FrameCallback {
    companion object {
        private const val W=1080f; private const val H=1920f; private const val GROUND=1690f
        private const val BX=300f; private const val BW=126f; private const val BH=99f
        private const val G=2500f; private const val FLAP=-820f; private const val SPEED=430f
        private const val GAP=600f; private const val PW=160f; private const val SPACING=620f
        private const val FIRST=1550f; private const val TRIGGER=480f
        private val SKY1=Color.rgb(67,174,226); private val SKY2=Color.rgb(222,242,246)
        private val BLUE=Color.rgb(28,77,108); private val GOLD=Color.rgb(236,164,52)
        private val TEXT=Color.rgb(28,58,76); private val MUTED=Color.rgb(92,119,133)
    }
    private enum class State{MENU,SETTINGS,PLAYING,GAMEOVER}
    private val prefs=context.getSharedPreferences("game",Context.MODE_PRIVATE)
    private val bird=BitmapFactory.decodeResource(resources,R.drawable.player_bird)
    private val frames=frames(bird)
    private val pipes=PipeSpawner(W,H,SPACING,PW,FIRST,TRIGGER,700f,990f,835f)
    private val sound=PremiumSoundEngine(); private val choreographer=Choreographer.getInstance()
    private val sky=Paint(1); private val cloud=Paint(1); private val mountain=Paint(1); private val city=Paint(1); private val ground=Paint(1); private val pipe=Paint(1); private val hi=Paint(1)
    private val birdPaint=Paint(Paint.ANTI_ALIAS_FLAG or Paint.FILTER_BITMAP_FLAG).apply{alpha=255;isFilterBitmap=true;isDither=true}
    private val hud=Paint(1); private val text=Paint(1); private val shadow=Paint(1); private val overlay=Paint(1); private val icon=Paint(1)
    private val dst=RectF(); private val hit=RectF(); private val topHit=RectF(); private val bottomHit=RectF(); private val scoreBox=RectF(); private val play=RectF(); private val second=RectF(); private val settings=RectF(); private val card=RectF(); private val record=RectF()
    private val mountainPath=Path(); private val snowPath=Path(); private val cityPath=Path()
    private val bold=Typeface.create("sans-serif",Typeface.BOLD); private val normal=Typeface.create("sans-serif",Typeface.NORMAL)
    private val skyShader=LinearGradient(0f,0f,0f,H,SKY1,SKY2,Shader.TileMode.CLAMP); private val pipeShader=LinearGradient(0f,0f,PW,0f,Color.rgb(88,184,153),Color.rgb(39,119,105),Shader.TileMode.CLAMP)
    private var state=State.MENU; private var score=0; private var high=prefs.getInt("high",0); private var previousHigh=high; private var newRecord=false; private var muted=prefs.getBoolean("muted",false); private var haptic=prefs.getBoolean("haptic",true)
    private var y=835f; private var v=0f; private var t=0f; private var over=0f; private var topInset=0f; private var bottomInset=0f; private var scale=1f; private var ox=0f; private var oy=0f
    private var running=false; private var posted=false; private var last=0L; private var framesDrawn=0L; private var seconds=0f; private var maxFrame=0f; private var callbacks=0L
    init{
        isFocusable=true;setLayerType(LAYER_TYPE_HARDWARE,null);text.typeface=bold;shadow.color=Color.argb(40,20,60,80);icon.style=Paint.Style.STROKE;icon.strokeCap=Paint.Cap.ROUND
        mountainPath.moveTo(0f,810f);mountainPath.cubicTo(180f,720f,315f,770f,425f,690f);mountainPath.lineTo(540f,385f);mountainPath.cubicTo(660f,680f,775f,735f,875f,670f);mountainPath.cubicTo(965f,615f,1030f,715f,W,745f);mountainPath.lineTo(W,1080f);mountainPath.lineTo(0f,1080f);mountainPath.close()
        snowPath.moveTo(475f,555f);snowPath.lineTo(540f,385f);snowPath.lineTo(610f,555f);snowPath.lineTo(573f,526f);snowPath.lineTo(540f,454f);snowPath.lineTo(507f,526f);snowPath.close()
        cityPath.moveTo(0f,1040f);cityPath.lineTo(90f,960f);cityPath.lineTo(175f,1040f);cityPath.lineTo(260f,930f);cityPath.lineTo(345f,1040f);cityPath.lineTo(430f,965f);cityPath.lineTo(515f,1040f);cityPath.lineTo(600f,905f);cityPath.lineTo(685f,1040f);cityPath.lineTo(770f,945f);cityPath.lineTo(855f,1040f);cityPath.lineTo(940f,920f);cityPath.lineTo(1025f,1040f);cityPath.lineTo(W,980f);cityPath.lineTo(W,1135f);cityPath.lineTo(0f,1135f);cityPath.close();startLoop()
    }
    override fun onAttachedToWindow(){super.onAttachedToWindow();startLoop()}
    override fun onDetachedFromWindow(){stopLoop();sound.release();frames.forEach{if(it!==bird&&!it.isRecycled)it.recycle()};if(!bird.isRecycled)bird.recycle();super.onDetachedFromWindow()}
    fun pauseLoop()=stopLoop();fun resumeLoop(){last=0L;startLoop()};fun setSafeInsets(top:Int,bottom:Int){topInset=top.toFloat();bottomInset=bottom.toFloat();resize(width,height);invalidate()}
    private fun startLoop(){if(running)return;running=true;last=0L;postFrame()};private fun stopLoop(){running=false;if(posted){choreographer.removeFrameCallback(this);posted=false};last=0L};private fun postFrame(){if(!running||posted)return;posted=true;choreographer.postFrameCallback(this)}
    override fun doFrame(now:Long){posted=false;if(!running)return;val raw=if(last==0L)0f else(now-last)/1_000_000_000f;last=now;val dt=raw.coerceIn(0f,.033f);if(BuildConfig.DEBUG){framesDrawn++;seconds+=raw.coerceAtLeast(0f);maxFrame=max(maxFrame,raw);callbacks++;if(framesDrawn%600L==0L)android.util.Log.d("ErciyesPerf","avgFPS=%.1f maxFrame=%.1fms callbacks=%d pipes=%d".format(if(seconds>0f)framesDrawn/seconds else 0f,maxFrame*1000f,callbacks,pipes.pipes.size))};update(dt);invalidate();postFrame()}
    private fun update(dt:Float){t+=dt;when(state){State.PLAYING->{v+=G*dt;y+=v*dt;pipes.update(dt,SPEED);for(p in pipes.pipes)if(!p.passed&&p.x+PW<BX&&pipes.markPassed(p))score++;if(collide())finish()};State.GAMEOVER->over=min(1f,over+dt*4f);else->{}}}
    private fun collide():Boolean{hit.set(BX-BW*.34f,y-BH*.36f,BX+BW*.34f,y+BH*.36f);if(hit.top<45f||hit.bottom>GROUND)return true;val h=GAP*.5f;for(p in pipes.pipes){topHit.set(p.x,0f,p.x+PW,p.gapCenter-h);bottomHit.set(p.x,p.gapCenter+h,p.x+PW,GROUND);if(RectF.intersects(hit,topHit)||RectF.intersects(hit,bottomHit))return true};return false}
    private fun finish(){if(state!=State.PLAYING)return;state=State.GAMEOVER;over=0f;newRecord=score>previousHigh;if(newRecord){high=score;prefs.edit().putInt("high",high).apply()};if(!muted)sound.play(6);buzz(HapticFeedbackConstants.LONG_PRESS)}
    private fun startGame(){state=State.PLAYING;score=0;previousHigh=high;newRecord=false;y=835f;v=0f;t=0f;pipes.reset();if(!muted)sound.play(5);buzz(HapticFeedbackConstants.VIRTUAL_KEY)}
    private fun menu(){state=State.MENU;pipes.clear()};private fun buzz(id:Int){if(haptic&&isHapticFeedbackEnabled)performHapticFeedback(id)}
    private fun resize(w:Int,h:Int){if(w<=0||h<=0)return;val usable=(h-topInset-bottomInset).coerceAtLeast(1f);scale=min(w/W,usable/H);ox=(w-W*scale)*.5f;oy=topInset+(usable-H*scale)*.5f}
    override fun onSizeChanged(w:Int,h:Int,ow:Int,oh:Int){super.onSizeChanged(w,h,ow,oh);resize(w,h)}
    override fun onTouchEvent(e:MotionEvent):Boolean{if(e.actionMasked!=MotionEvent.ACTION_DOWN)return true;val x=(e.x-ox)/scale;val z=(e.y-oy)/scale;when(state){State.MENU->if(play.contains(x,z))startGame()else if(settings.contains(x,z))state=State.SETTINGS;State.SETTINGS->if(play.contains(x,z)){haptic=!haptic;prefs.edit().putBoolean("haptic",haptic).apply()}else if(second.contains(x,z)){muted=!muted;prefs.edit().putBoolean("muted",muted).apply()}else if(settings.contains(x,z))menu();State.PLAYING->{v=FLAP;if(!muted)sound.play(1);buzz(HapticFeedbackConstants.KEYBOARD_TAP)};State.GAMEOVER->if(play.contains(x,z))startGame()else if(second.contains(x,z))menu()};return true}
    override fun onDraw(c:Canvas){super.onDraw(c);c.drawColor(SKY2);c.save();c.translate(ox,oy);c.scale(scale,scale);world(c);when(state){State.MENU->menuDraw(c);State.SETTINGS->settingsDraw(c);State.PLAYING->hudDraw(c);State.GAMEOVER->{hudDraw(c);overDraw(c)}};c.restore()}
    private fun world(c:Canvas){sky.shader=skyShader;sky.alpha=255;c.drawRect(0f,0f,W,H,sky);sky.shader=null;clouds(c);mountain.color=Color.rgb(94,155,192);mountain.alpha=255;c.drawPath(mountainPath,mountain);mountain.color=Color.rgb(246,251,251);c.drawPath(snowPath,mountain);city.color=Color.rgb(126,159,172);city.alpha=205;c.drawPath(cityPath,city);city.color=Color.rgb(174,195,201);city.alpha=180;c.drawRect(450f,940f,630f,1045f,city);c.drawOval(460f,830f,620f,955f,city);ground.color=Color.rgb(82,166,93);ground.alpha=255;c.drawRect(0f,GROUND,W,GROUND+40f,ground);ground.color=Color.rgb(238,211,158);c.drawRect(0f,GROUND+40f,W,H,ground);drawPipes(c);drawBird(c,state==State.MENU)}
    private fun clouds(c:Canvas){cloud(c,120f-t*7f,245f,100f);cloud(c,730f-t*4f,345f,115f);cloud(c,1270f-t*2.5f,175f,80f)}
    private fun cloud(c:Canvas,x:Float,z:Float,s:Float){val q=((x+1400f)%1400f)-150f;cloud.color=Color.WHITE;cloud.alpha=205;c.drawCircle(q,z,s*.3f,cloud);c.drawCircle(q+s*.3f,z-s*.09f,s*.39f,cloud);c.drawCircle(q+s*.6f,z,s*.27f,cloud);c.drawRoundRect(q-s*.27f,z,q+s*.72f,z+s*.2f,s*.1f,s*.1f,cloud)}
    private fun drawPipes(c:Canvas){val h=GAP*.5f;for(p in pipes.pipes){pipe.shader=pipeShader;pipe.alpha=255;c.drawRoundRect(p.x,0f,p.x+PW,p.gapCenter-h,15f,15f,pipe);c.drawRoundRect(p.x,p.gapCenter+h,p.x+PW,GROUND,15f,15f,pipe);pipe.shader=null;pipe.color=Color.rgb(75,139,177);c.drawRoundRect(p.x-14f,p.gapCenter-h-48f,p.x+PW+14f,p.gapCenter-h,14f,14f,pipe);c.drawRoundRect(p.x-14f,p.gapCenter+h,p.x+PW+14f,p.gapCenter+h+48f,14f,14f,pipe);hi.color=Color.rgb(141,221,190);hi.alpha=125;c.drawRoundRect(p.x+13f,8f,p.x+29f,max(9f,p.gapCenter-h-8f),7f,7f,hi);c.drawRoundRect(p.x+13f,p.gapCenter+h+8f,p.x+29f,GROUND-8f,7f,7f,hi)}}
    private fun drawBird(c:Canvas,menu:Boolean){birdPaint.alpha=255;birdPaint.colorFilter=null;val yy=if(menu)735f+sin(t*2f)*9f else y;val f=frames[((t*8f).toInt()%frames.size+frames.size)%frames.size];dst.set(BX-BW*.5f,yy-BH*.5f,BX+BW*.5f,yy+BH*.5f);c.save();c.rotate(if(menu)sin(t*1.5f)*4f else(v/24f).coerceIn(-20f,22f),BX,yy);c.drawBitmap(f,null,dst,birdPaint);c.restore()}
    private fun hudDraw(c:Canvas){scoreBox.set(430f,58f,650f,166f);hud.color=Color.WHITE;hud.alpha=240;c.drawRoundRect(scoreBox,28f,28f,hud);text.typeface=bold;text.color=TEXT;text.textAlign=Paint.Align.CENTER;text.textSize=68f;text.alpha=255;c.drawText(score.toString(),540f,136f,text)}
    private fun button(c:Canvas,r:RectF,label:String,primary:Boolean){shadow.alpha=35;c.drawRoundRect(r.left+4f,r.top+7f,r.right+4f,r.bottom+7f,30f,30f,shadow);hud.color=if(primary)GOLD else Color.rgb(238,247,249);hud.alpha=255;c.drawRoundRect(r,30f,30f,hud);text.typeface=bold;text.textSize=if(primary)48f else 28f;text.color=if(primary)BLUE else TEXT;text.textAlign=Paint.Align.CENTER;c.drawText(label,r.centerX(),r.centerY()+text.textSize*.34f,text)}
    private fun menuDraw(c:Canvas){card.set(110f,165f,970f,1645f);hud.color=Color.WHITE;hud.alpha=190;c.drawRoundRect(card,56f,56f,hud);text.typeface=bold;text.color=BLUE;text.textSize=84f;text.textAlign=Paint.Align.CENTER;c.drawText("ERCİYES",540f,385f,text);text.typeface=normal;text.color=GOLD;text.textSize=54f;c.drawText("UÇUŞU",540f,445f,text);text.color=MUTED;text.textSize=29f;c.drawText("Kayseri'nin üzerinde ne kadar uçabilirsin?",540f,885f,text);play.set(280f,1010f,800f,1150f);second.set(350f,1190f,730f,1300f);settings.set(455f,1360f,625f,1465f);button(c,play,"OYNA",true);button(c,second,if(muted)"SES KAPALI" else "SES AÇIK",false);hud.color=Color.rgb(238,247,249);hud.alpha=255;c.drawCircle(540f,1412f,48f,hud);text.typeface=bold;text.color=TEXT;text.textSize=27f;c.drawText("EN YÜKSEK SKOR  $high",540f,1550f,text)}
    private fun settingsDraw(c:Canvas){card.set(160f,620f,920f,1395f);hud.color=Color.WHITE;hud.alpha=245;c.drawRoundRect(card,48f,48f,hud);text.typeface=bold;text.color=TEXT;text.textSize=48f;text.textAlign=Paint.Align.CENTER;c.drawText("AYARLAR",540f,735f,text);play.set(270f,820f,810f,960f);second.set(270f,1000f,810f,1140f);settings.set(455f,1220f,625f,1325f);button(c,play,if(haptic)"TİTREŞİM AÇIK" else "TİTREŞİM KAPALI",true);button(c,second,if(muted)"SES KAPALI" else "SES AÇIK",false);button(c,settings,"GERİ",false)}
    private fun overDraw(c:Canvas){overlay.color=Color.rgb(20,58,74);overlay.alpha=(145f*min(1f,over*2.2f)).toInt();c.drawRect(0f,0f,W,H,overlay);card.set(180f,565f,900f,1285f);hud.color=Color.WHITE;hud.alpha=255;c.drawRoundRect(card,46f,46f,hud);text.typeface=bold;text.color=TEXT;text.textSize=56f;text.textAlign=Paint.Align.CENTER;c.drawText("OYUN BİTTİ",540f,670f,text);text.typeface=normal;text.color=MUTED;text.textSize=25f;c.drawText("Uçuş tamamlandı",540f,715f,text);text.typeface=bold;text.color=BLUE;text.textSize=104f;c.drawText(score.toString(),540f,845f,text);text.typeface=normal;text.color=MUTED;text.textSize=25f;c.drawText("SKOR",540f,890f,text);text.textAlign=Paint.Align.LEFT;text.textSize=26f;c.drawText("EN YÜKSEK",340f,965f,text);text.textAlign=Paint.Align.RIGHT;text.typeface=bold;text.color=TEXT;c.drawText(high.toString(),740f,965f,text);if(newRecord){record.set(370f,998f,710f,1056f);hud.color=Color.rgb(255,244,215);hud.alpha=255;c.drawRoundRect(record,28f,28f,hud);text.textAlign=Paint.Align.CENTER;text.color=Color.rgb(170,112,24);text.textSize=24f;c.drawText("YENİ REKOR",540f,1037f,text)};play.set(280f,1090f,800f,1190f);second.set(325f,1205f,755f,1270f);button(c,play,"TEKRAR OYNA",true);button(c,second,"ANA MENÜ",false)}
    private fun frames(src:Bitmap):Array<Bitmap>{val out=ArrayList<Bitmap>(3);for(s in floatArrayOf(.97f,1f,1.03f)){val m=Matrix();m.setScale(1f,s,src.width/2f,src.height/2f);out+=Bitmap.createBitmap(src,0,0,src.width,src.height,m,true)};return out.toTypedArray()}
}
